#!/bin/sh
# This shell script is PUBLIC DOMAIN. You may do whatever you want with it.

TOGGLE=$HOME/.toggle_touchpad

if [ ! -e $TOGGLE ]; then
    touch $TOGGLE
    # Disable touchpad
    xinput list | grep -i touchpad | while read -r line; do
        id=$(echo "$line" | sed -n 's/.*id=\([0-9]\+\).*/\1/p')
        if [ -n "$id" ]; then
            xinput disable "$id"
        fi
    done
    notify-send -u low -i mouse --icon=/usr/share/icons/HighContrast/256x256/status/touchpad-disabled.png "Trackpad disabled"
else
    rm $TOGGLE
    # Enable touchpad
    xinput list | grep -i touchpad | while read -r line; do
        id=$(echo "$line" | sed -n 's/.*id=\([0-9]\+\).*/\1/p')
        if [ -n "$id" ]; then
            xinput enable "$id"
        fi
    done
    notify-send -u low -i mouse --icon=/usr/share/icons/HighContrast/256x256/devices/input-touchpad.png "Trackpad enabled"
fi
