#!/bin/sh
echo "Insert link here: "
read LINK 
yt-dlp $LINK -x --audio-format mp3 --audio-quality 320k --ppa "ThumbnailsConvertor+FFmpeg_o:-c:v mjpeg -vf crop=\"'if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'\"" --embed-thumbnail --embed-chapters --embed-metadata
